using Autofac;
using System;
using System.Collections.Generic;
using Whitespace;

namespace ConferenceSchedule10
{
    class Program
    {
        static List<string> _eventsInput = new()
        {
            { "Proper Unit Tests for Anyone 1min" },
            { "Why Python ? 2min" },
            { "TDD for Embedded Systems 3min" },
            { "Dependency Management with Interpreted languages 4min" },
            { "Java, really end of life 5min" },
            { "From Java to Java lightning" },
            { "Managing Network Latency 6min" },
            { "BDD Gone Mad 7min" },
            { "Do you smell that ? (Code Smells) 8min" },
            { "Open Office Space or Closets ???? 9min" },
            { "Proper Pairing 10min" },
            { "Spring JuJu 11min" },
            { "Effective DSL(Domain Specific Languages) 12min" },
            { "Clojure... What Happened(on my project) 13min" },
            { "Effective Legacy Code Techniques... 14min" },
            { "Backends and FrontEnds in JavaScript ? 15min" },
            { "CD on the Mainframe 16min" },
            { "Making Windows Development Enjoyable... 17min" },
            { "Modern Build Systems 18min" },

            { "TDD 19min" },
            { "BDD 20min" },
            { "Law of Demeter and U 21min" },
            { "Trendy Tech Acronyms 22min" },
            { "RU leet enough? 23min" },
            { "Impressing others by Blogging lightning" },
            { "Twitter Burns You Can Use lightning" },
            { "How to Get A Girlfriend lightning" },
            { "Funny things About Frogs lightning" },
            { "The Next Coolest JS Framework lightning" },
            { "Debugging for Fun and Profit 24min" },
            { "Amusing T-Shirt Design Contest 25min" },
            { "Coffee Curation for Nerds 26min" },
            { "Is Your Code Woke Enough? 27min" },
            { "Mega Extreme Extreme Programming  28min" },
            { "Circle the Bandwagons 29min" },
            { "Stack Overflow 30min" },
            { "Spreadsheets 31min" },
            { "Refactoring 32min" },
            { "System Design 33min" },
            { "Cloud Architecture Patterns 34min" },
            { "Wintermute 35min" },
            { "Technolycanthropy 36min" },

            { "Open source: how to work for free 37min" },
            { "EndDowns: The new Startups 38m" },
            { "Instagram Filters to Make You look Like a Leader 39min" },
            { "Be Heard : Why Listen When You can Talk? 40min" },
            { "Modern History: Revisiting Obselete Tech from Two Years Ago 41min" },
            { "Raising your Children From Inside a Cubicle lightning" },
            { "Power Moves: Thumb Exercises to Type Faster on Mobile Devices 42min" },
            { "Round-Table: Stare at your Eletronic Device With Others for 43min" },
            { "Pokemon Tournament 44min" },
            { "Tips For Appearing Productive 45min" },
            { "Hyper-Coding : The Next Neologism! 46min" },
            { "[Interactive Display] Ferris Wheel of Tech-Churn (Child-Friendly Event) 47min" },
            { "Bio-Hack your BMI 48min" },
            { "Social Networks for Unsocial People 49min" },
            { "Powering Hacking for 10xers Who Are Rockstars 50min" },
            { "[Interactive Display] Mechanical Keyboard Noise-making Symphony 51min" },
            { "Electronic Communications In a World of Humans 52min" },
            { "Duct-Tape it! How To Kick The Can a few Years Down the Road for Someone Else to Deal With 53min" },
            { "Listen to My Talk So I Can take a Photo for my LinkedIn Profile 54min" },

            { "Proper Unit Tests for Anyone 1min" },
            { "Why Python ? 2min" },
            { "TDD for Embedded Systems 3min" },
            { "Dependency Management with Interpreted languages 4min" },
            { "Java, really end of life 5min" },
            { "From Java to Java lightning" },
            { "Managing Network Latency 6min" },
            { "BDD Gone Mad 7min" },
            { "Do you smell that ? (Code Smells) 8min" },
            { "Open Office Space or Closets ???? 9min" },
            { "Proper Pairing 10min" },
            { "Spring JuJu 11min" },
            { "Effective DSL(Domain Specific Languages) 12min" },
            { "Clojure... What Happened(on my project) 13min" },
            { "Effective Legacy Code Techniques... 14min" },
            { "Backends and FrontEnds in JavaScript ? 15min" },
            { "CD on the Mainframe 16min" },
            { "Making Windows Development Enjoyable... 17min" },
            { "Modern Build Systems 18min" },

            { "TDD 19min" },
            { "BDD 20min" },
            { "Law of Demeter and U 21min" },
            { "Trendy Tech Acronyms 22min" },
            { "RU leet enough? 23min" },
            { "Impressing others by Blogging lightning" },
            { "Twitter Burns You Can Use lightning" },
            { "How to Get A Girlfriend lightning" },
            { "Funny things About Frogs lightning" },
            { "The Next Coolest JS Framework lightning" },
            { "Debugging for Fun and Profit 24min" },
            { "Amusing T-Shirt Design Contest 25min" },
            { "Coffee Curation for Nerds 26min" },
            { "Is Your Code Woke Enough? 27min" },
            { "Mega Extreme Extreme Programming  28min" },
            { "Circle the Bandwagons 29min" },
            { "Stack Overflow 30min" },
            { "Spreadsheets 31min" },
            { "Refactoring 32min" },
            { "System Design 33min" },
            { "Cloud Architecture Patterns 34min" },
            { "Wintermute 35min" },
            { "Technolycanthropy 36min" },

            { "Open source: how to work for free 37min" },
            { "EndDowns: The new Startups 38m" },
            { "Instagram Filters to Make You look Like a Leader 39min" },
            { "Be Heard : Why Listen When You can Talk? 40min" },
            { "Modern History: Revisiting Obselete Tech from Two Years Ago 41min" },
            { "Raising your Children From Inside a Cubicle lightning" },
            { "Power Moves: Thumb Exercises to Type Faster on Mobile Devices 42min" },
            { "Round-Table: Stare at your Eletronic Device With Others for 43min" },
            { "Pokemon Tournament 44min" },
            { "Tips For Appearing Productive 45min" },
            { "Hyper-Coding : The Next Neologism! 46min" },
            { "[Interactive Display] Ferris Wheel of Tech-Churn (Child-Friendly Event) 47min" },
            { "Bio-Hack your BMI 48min" },
            { "Social Networks for Unsocial People 49min" },
            { "Powering Hacking for 10xers Who Are Rockstars 50min" },
            { "[Interactive Display] Mechanical Keyboard Noise-making Symphony 51min" },
            { "Electronic Communications In a World of Humans 52min" },
            { "Duct-Tape it! How To Kick The Can a few Years Down the Road for Someone Else to Deal With 53min" },
            { "Listen to My Talk So I Can take a Photo for my LinkedIn Profile 54min" },

            { "Proper Unit Tests for Anyone 1min" },
            { "Why Python ? 2min" },
            { "TDD for Embedded Systems 3min" },
            { "Dependency Management with Interpreted languages 4min" },
            { "Java, really end of life 5min" },
            { "From Java to Java lightning" },
            { "Managing Network Latency 6min" },
            { "BDD Gone Mad 7min" },
            { "Do you smell that ? (Code Smells) 8min" },
            { "Open Office Space or Closets ???? 9min" },
            { "Proper Pairing 10min" },
            { "Spring JuJu 11min" },
            { "Effective DSL(Domain Specific Languages) 12min" },
            { "Clojure... What Happened(on my project) 13min" },
            { "Effective Legacy Code Techniques... 14min" },
            { "Backends and FrontEnds in JavaScript ? 15min" },
            { "CD on the Mainframe 16min" },
            { "Making Windows Development Enjoyable... 17min" },
            { "Modern Build Systems 18min" },

            { "TDD 19min" },
            { "BDD 20min" },
            { "Law of Demeter and U 21min" },
            { "Trendy Tech Acronyms 22min" },
            { "RU leet enough? 23min" },
            { "Impressing others by Blogging lightning" },
            { "Twitter Burns You Can Use lightning" },
            { "How to Get A Girlfriend lightning" },
            { "Funny things About Frogs lightning" },
            { "The Next Coolest JS Framework lightning" },
            { "Debugging for Fun and Profit 24min" },
            { "Amusing T-Shirt Design Contest 25min" },
            { "Coffee Curation for Nerds 26min" },
            { "Is Your Code Woke Enough? 27min" },
            { "Mega Extreme Extreme Programming  28min" },
            { "Circle the Bandwagons 29min" },
            { "Stack Overflow 30min" },
            { "Spreadsheets 31min" },
            { "Refactoring 32min" },
            { "System Design 33min" },
            { "Cloud Architecture Patterns 34min" },
            { "Wintermute 35min" },
            { "Technolycanthropy 36min" },

            { "Open source: how to work for free 37min" },
            { "EndDowns: The new Startups 38m" },
            { "Instagram Filters to Make You look Like a Leader 39min" },
            { "Be Heard : Why Listen When You can Talk? 40min" },
            { "Modern History: Revisiting Obselete Tech from Two Years Ago 41min" },
            { "Raising your Children From Inside a Cubicle lightning" },
            { "Power Moves: Thumb Exercises to Type Faster on Mobile Devices 42min" },
            { "Round-Table: Stare at your Eletronic Device With Others for 43min" },
            { "Pokemon Tournament 44min" },
            { "Tips For Appearing Productive 45min" },
            { "Hyper-Coding : The Next Neologism! 46min" },
            { "[Interactive Display] Ferris Wheel of Tech-Churn (Child-Friendly Event) 47min" },
            { "Bio-Hack your BMI 48min" },
            { "Social Networks for Unsocial People 49min" },
            { "Powering Hacking for 10xers Who Are Rockstars 50min" },
            { "[Interactive Display] Mechanical Keyboard Noise-making Symphony 51min" },
            { "Electronic Communications In a World of Humans 52min" },
            { "Duct-Tape it! How To Kick The Can a few Years Down the Road for Someone Else to Deal With 53min" },
            { "Listen to My Talk So I Can take a Photo for my LinkedIn Profile 54min" },

            { "Proper Unit Tests for Anyone 1min" },
            { "Why Python ? 2min" },
            { "TDD for Embedded Systems 3min" },
            { "Dependency Management with Interpreted languages 4min" },
            { "Java, really end of life 5min" },
            { "From Java to Java lightning" },
            { "Managing Network Latency 6min" },
            { "BDD Gone Mad 7min" },
            { "Do you smell that ? (Code Smells) 8min" },
            { "Open Office Space or Closets ???? 9min" },
            { "Proper Pairing 10min" },
            { "Spring JuJu 11min" },
            { "Effective DSL(Domain Specific Languages) 12min" },
            { "Clojure... What Happened(on my project) 13min" },
            { "Effective Legacy Code Techniques... 14min" },
            { "Backends and FrontEnds in JavaScript ? 15min" },
            { "CD on the Mainframe 16min" },
            { "Making Windows Development Enjoyable... 17min" },
            { "Modern Build Systems 18min" },

            { "TDD 19min" },
            { "BDD 20min" },
            { "Law of Demeter and U 21min" },
            { "Trendy Tech Acronyms 22min" },
            { "RU leet enough? 23min" },
            { "Impressing others by Blogging lightning" },
            { "Twitter Burns You Can Use lightning" },
            { "How to Get A Girlfriend lightning" },
            { "Funny things About Frogs lightning" },
            { "The Next Coolest JS Framework lightning" },
            { "Debugging for Fun and Profit 24min" },
            { "Amusing T-Shirt Design Contest 25min" },
            { "Coffee Curation for Nerds 26min" },
            { "Is Your Code Woke Enough? 27min" },
            { "Mega Extreme Extreme Programming  28min" },
            { "Circle the Bandwagons 29min" },
            { "Stack Overflow 30min" },
            { "Spreadsheets 31min" },
            { "Refactoring 32min" },
            { "System Design 33min" },
            { "Cloud Architecture Patterns 34min" },
            { "Wintermute 35min" },
            { "Technolycanthropy 36min" },

            { "Open source: how to work for free 37min" },
            { "EndDowns: The new Startups 38m" },
            { "Instagram Filters to Make You look Like a Leader 39min" },
            { "Be Heard : Why Listen When You can Talk? 40min" },
            { "Modern History: Revisiting Obselete Tech from Two Years Ago 41min" },
            { "Raising your Children From Inside a Cubicle lightning" },
            { "Power Moves: Thumb Exercises to Type Faster on Mobile Devices 42min" },
            { "Round-Table: Stare at your Eletronic Device With Others for 43min" },
            { "Pokemon Tournament 44min" },
            { "Tips For Appearing Productive 45min" },
            { "Hyper-Coding : The Next Neologism! 46min" },
            { "[Interactive Display] Ferris Wheel of Tech-Churn (Child-Friendly Event) 47min" },
            { "Bio-Hack your BMI 48min" },
            { "Social Networks for Unsocial People 49min" },
            { "Powering Hacking for 10xers Who Are Rockstars 50min" },
            { "[Interactive Display] Mechanical Keyboard Noise-making Symphony 51min" },
            { "Electronic Communications In a World of Humans 52min" },
            { "Duct-Tape it! How To Kick The Can a few Years Down the Road for Someone Else to Deal With 53min" },
            { "Listen to My Talk So I Can take a Photo for my LinkedIn Profile 54min" }
        };

        static Program()
        {
            _eventsInput.ForEach(str => _events.Add(new Event(str)));

            var builder = new ContainerBuilder();
            builder.RegisterType<TrackFactory>().As<ITrackFactory>();
            builder.RegisterType<SessionFactory>().As<ISessionFactory>();
            builder.RegisterType<EventListFacadeFactory>().As<IEventListFacadeFactory>();
            builder.RegisterType<DeepTrackScheduler>().Named<ITrackScheduler>("deepTrack");
            builder.RegisterType<TrackSchedulePrinter>().As<ITrackSchedulePrinter>();
            Container = builder.Build();
        }

        private static List<Event> _events = new();
        private static IContainer Container { get; set; }

        static void Main(string[] args)
        {
            using var scope = Container.BeginLifetimeScope();
            var eventScheduler = scope.ResolveNamed<ITrackScheduler>("deepTrack");
            IEnumerable<ITrack> scheduledEvents1 = eventScheduler.Schedule(_events);
            string scheduledEvents1string = eventScheduler.Print(scheduledEvents1);

            Console.WriteLine(scheduledEvents1string);
            Console.ReadLine();
        }
    }
}
